apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-single
  namespace: minio-tenant
spec:
  configuration:
    name: storage-configuration  
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: local-storage
  mountPath: /data
  requestAutoCert: false