apiVersion: v1
kind: Pod
metadata:
  name: ws-scraper
  labels:
    app: ws-scraper
spec:
  containers:
  - name: ws-scraper
    image: ws_scraper:v1.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - name: config-volume
      mountPath: /app/config/config.yaml
      subPath: config.yaml
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTHONPATH
      value: /app
    - name: ALPACA_KEY
      valueFrom:
        secretKeyRef:
          name: alpaca-creds
          key: ALPACA_KEY
    - name: ALPACA_SECRET
      valueFrom:
        secretKeyRef:
          name: alpaca-creds
          key: ALPACA_SECRET
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  restartPolicy: Never