apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
        - name: jupyter
          image: my-jupyter-image:v1
          imagePullPolicy: Never
          args: [
            "start-notebook.sh",
            "--NotebookApp.token='minikube123'",
            "--NotebookApp.allow_origin='*'",
            "--NotebookApp.ip=0.0.0.0"
          ]
          env:
            - name: NOTEBOOK_DIR
              value: /mnt/data
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: notebook-volume
              mountPath: /mnt/data
      volumes:
        - name: notebook-volume
          hostPath:
            path: /mnt/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30031
